// SPDX-License-Identifier: GPL-3.0-or-later
// <auto-generated> by CommandBar/Data/generate_data.py from the Unicode Character Database
// (Unicode 16.0.0) and emoji-test.txt. Do not edit by hand.
namespace Rivet.Core.Launcher;

internal static class EmojiData
{
    /// <summary>Popular emoji in display order: "glyph\tname" lines.</summary>
    public const string Popular =
        "😀	grinning face\n" +
        "😃	smiling face with open mouth\n" +
        "😄	smiling face with open mouth and smiling eyes\n" +
        "😁	grinning face with smiling eyes\n" +
        "😆	smiling face with open mouth and tightly-closed eyes\n" +
        "😅	smiling face with open mouth and cold sweat\n" +
        "🤣	rolling on the floor laughing\n" +
        "😂	face with tears of joy\n" +
        "🙂	slightly smiling face\n" +
        "🙃	upside-down face\n" +
        "😉	winking face\n" +
        "😊	smiling face with smiling eyes\n" +
        "😍	smiling face with heart-shaped eyes\n" +
        "🥰	smiling face with smiling eyes and three hearts\n" +
        "😘	face throwing a kiss\n" +
        "😗	kissing face\n" +
        "😜	face with stuck-out tongue and winking eye\n" +
        "🤪	grinning face with one large and one small eye\n" +
        "🤔	thinking face\n" +
        "🤗	hugging face\n" +
        "🤩	grinning face with star eyes\n" +
        "🥳	face with party horn and party hat\n" +
        "😎	smiling face with sunglasses\n" +
        "🤓	nerd face\n" +
        "😐	neutral face\n" +
        "😑	expressionless face\n" +
        "😶	face without mouth\n" +
        "🙄	face with rolling eyes\n" +
        "😏	smirking face\n" +
        "😥	disappointed but relieved face\n" +
        "😮	face with open mouth\n" +
        "😴	sleeping face\n" +
        "😌	relieved face\n" +
        "😔	pensive face\n" +
        "😪	sleepy face\n" +
        "🤤	drooling face\n" +
        "😭	loudly crying face\n" +
        "😢	crying face\n" +
        "😤	face with look of triumph\n" +
        "😠	angry face\n" +
        "😡	pouting face\n" +
        "🤬	serious face with symbols covering mouth\n" +
        "🤯	shocked face with exploding head\n" +
        "😳	flushed face\n" +
        "🥺	face with pleading eyes\n" +
        "😱	face screaming in fear\n" +
        "😨	fearful face\n" +
        "😰	face with open mouth and cold sweat\n" +
        "💀	skull\n" +
        "☠️	skull and crossbones\n" +
        "🙏	person with folded hands\n" +
        "👍	thumbs up sign\n" +
        "👎	thumbs down sign\n" +
        "👌	ok hand sign\n" +
        "🤌	pinched fingers\n" +
        "✌️	victory hand\n" +
        "🤞	hand with index and middle fingers crossed\n" +
        "🤟	i love you hand sign\n" +
        "🤘	sign of the horns\n" +
        "👏	clapping hands sign\n" +
        "🙌	person raising both hands in celebration\n" +
        "👐	open hands sign\n" +
        "💪	flexed biceps\n" +
        "🫶	heart hands\n" +
        "👋	waving hand sign\n" +
        "🤝	handshake\n" +
        "✍️	writing hand\n" +
        "💅	nail polish\n" +
        "👀	eyes\n" +
        "🧠	brain\n" +
        "🫀	anatomical heart\n" +
        "🦾	mechanical arm\n" +
        "🦿	mechanical leg\n" +
        "👣	footprints\n" +
        "❤️	heavy black heart\n" +
        "🧡	orange heart\n" +
        "💛	yellow heart\n" +
        "💚	green heart\n" +
        "💙	blue heart\n" +
        "💜	purple heart\n" +
        "🖤	black heart\n" +
        "🤍	white heart\n" +
        "💔	broken heart\n" +
        "❣️	heavy heart exclamation mark ornament\n" +
        "💕	two hearts\n" +
        "💞	revolving hearts\n" +
        "🔥	fire\n" +
        "✨	sparkles\n" +
        "⭐️	white medium star\n" +
        "🌟	glowing star\n" +
        "💫	dizzy symbol\n" +
        "⚡️	high voltage sign\n" +
        "☀️	black sun with rays\n" +
        "🌤	white sun with small cloud\n" +
        "☁️	cloud\n" +
        "🌧	cloud with rain\n" +
        "⛈	thunder cloud and rain\n" +
        "❄️	snowflake\n" +
        "🎉	party popper\n" +
        "🎊	confetti ball\n" +
        "🎁	wrapped present\n" +
        "🎂	birthday cake\n" +
        "🍰	shortcake\n" +
        "🍕	slice of pizza\n" +
        "🍔	hamburger\n" +
        "🍟	french fries\n" +
        "🌮	taco\n" +
        "🍣	sushi\n" +
        "🍎	red apple\n" +
        "🍌	banana\n" +
        "☕️	hot beverage\n" +
        "🍺	beer mug\n" +
        "🍻	clinking beer mugs\n" +
        "🥂	clinking glasses\n" +
        "🍷	wine glass\n" +
        "🧉	mate drink\n" +
        "🥤	cup with straw\n" +
        "🍫	chocolate bar\n" +
        "🍪	cookie\n" +
        "🍩	doughnut\n" +
        "🥐	croissant\n" +
        "🧀	cheese wedge\n" +
        "🚀	rocket\n" +
        "✈️	airplane\n" +
        "🚗	automobile\n" +
        "🚕	taxi\n" +
        "🚲	bicycle\n" +
        "🛴	scooter\n" +
        "🏠	house building\n" +
        "🏢	office building\n" +
        "🌍	earth globe europe-africa\n" +
        "🌎	earth globe americas\n" +
        "🌏	earth globe asia-australia\n" +
        "🗺	world map\n" +
        "💻	personal computer\n" +
        "🖥	desktop computer\n" +
        "⌨️	keyboard\n" +
        "🖱	three button mouse\n" +
        "📱	mobile phone\n" +
        "⌚️	watch\n" +
        "🎧	headphone\n" +
        "📷	camera\n" +
        "🔋	battery\n" +
        "💾	floppy disk\n" +
        "🖨	printer\n" +
        "📡	satellite antenna\n" +
        "📁	file folder\n" +
        "📂	open file folder\n" +
        "📄	page facing up\n" +
        "📌	pushpin\n" +
        "📎	paperclip\n" +
        "🔖	bookmark\n" +
        "🔍	left-pointing magnifying glass\n" +
        "🔒	lock\n" +
        "🔓	open lock\n" +
        "🔑	key\n" +
        "🛠	hammer and wrench\n" +
        "⚙️	gear\n" +
        "✅	white heavy check mark\n" +
        "❌	cross mark\n" +
        "⚠️	warning sign\n" +
        "❓	black question mark ornament\n" +
        "❗️	heavy exclamation mark symbol\n" +
        "💡	electric light bulb\n" +
        "🔔	bell\n" +
        "🔕	bell with cancellation stroke\n" +
        "♻️	black universal recycling symbol\n" +
        "🆗	squared ok\n" +
        "🆕	squared new\n" +
        "🔝	top with upwards arrow above\n" +
        "🐶	dog face\n" +
        "🐱	cat face\n" +
        "🐭	mouse face\n" +
        "🐰	rabbit face\n" +
        "🦊	fox face\n" +
        "🐻	bear face\n" +
        "🐼	panda face\n" +
        "🐨	koala\n" +
        "🦁	lion face\n" +
        "🐮	cow face\n" +
        "🐷	pig face\n" +
        "🐸	frog face\n" +
        "🌱	seedling\n" +
        "🌲	evergreen tree\n" +
        "🌳	deciduous tree\n" +
        "🌴	palm tree\n" +
        "🌵	cactus\n" +
        "🌷	tulip\n" +
        "🌸	cherry blossom\n" +
        "🌹	rose\n" +
        "🌺	hibiscus\n" +
        "🌻	sunflower\n" +
        "🍀	four leaf clover\n" +
        "🍁	maple leaf\n" +
        "⏰	alarm clock\n" +
        "⏳	hourglass with flowing sand\n" +
        "📅	calendar\n" +
        "📈	chart with upwards trend\n" +
        "📉	chart with downwards trend\n" +
        "📊	bar chart\n" +
        "💰	money bag\n" +
        "💳	credit card\n" +
        "🏆	trophy\n" +
        "🥇	first place medal\n" +
        "🎯	direct hit\n" +
        "🧩	jigsaw puzzle piece";

    /// <summary>Every other emoji scalar, sorted by name: "glyph\tname" lines.</summary>
    public const string LongTail =
        "🧮	abacus\n" +
        "🪗	accordion\n" +
        "🩹	adhesive bandage\n" +
        "🎟️	admission tickets\n" +
        "🧑	adult\n" +
        "🚡	aerial tramway\n" +
        "🛬	airplane arriving\n" +
        "🛫	airplane departure\n" +
        "⚗️	alembic\n" +
        "👾	alien monster\n" +
        "🚑	ambulance\n" +
        "🏈	american football\n" +
        "🏺	amphora\n" +
        "⚓	anchor\n" +
        "💢	anger symbol\n" +
        "😧	anguished face\n" +
        "🐜	ant\n" +
        "📶	antenna with bars\n" +
        "🔄	anticlockwise downwards and upwards open circle arrows\n" +
        "♒	aquarius\n" +
        "♈	aries\n" +
        "⤵️	arrow pointing rightwards then curving downwards\n" +
        "⤴️	arrow pointing rightwards then curving upwards\n" +
        "🚛	articulated lorry\n" +
        "🎨	artist palette\n" +
        "😲	astonished face\n" +
        "👟	athletic shoe\n" +
        "⚛️	atom symbol\n" +
        "🍆	aubergine\n" +
        "🛺	auto rickshaw\n" +
        "🏧	automated teller machine\n" +
        "🥑	avocado\n" +
        "🪓	axe\n" +
        "👶	baby\n" +
        "👼	baby angel\n" +
        "🍼	baby bottle\n" +
        "🐤	baby chick\n" +
        "🚼	baby symbol\n" +
        "🔙	back with leftwards arrow above\n" +
        "🥓	bacon\n" +
        "🐫	bactrian camel\n" +
        "🦡	badger\n" +
        "🏸	badminton racquet and shuttlecock\n" +
        "🥯	bagel\n" +
        "🛄	baggage claim\n" +
        "🥖	baguette bread\n" +
        "🧶	ball of yarn\n" +
        "🩰	ballet shoes\n" +
        "🎈	balloon\n" +
        "🗳️	ballot box with ballot\n" +
        "☑️	ballot box with check\n" +
        "🪕	banjo\n" +
        "🏦	bank\n" +
        "💵	banknote with dollar sign\n" +
        "💶	banknote with euro sign\n" +
        "💷	banknote with pound sign\n" +
        "💴	banknote with yen sign\n" +
        "🧼	bar of soap\n" +
        "💈	barber pole\n" +
        "⚾	baseball\n" +
        "🧺	basket\n" +
        "🏀	basketball and hoop\n" +
        "🦇	bat\n" +
        "🛀	bath\n" +
        "🛁	bathtub\n" +
        "🏖️	beach with umbrella\n" +
        "🫘	beans\n" +
        "🧔	bearded person\n" +
        "💓	beating heart\n" +
        "🦫	beaver\n" +
        "🛏️	bed\n" +
        "🪲	beetle\n" +
        "🫑	bell pepper\n" +
        "🛎️	bellhop bell\n" +
        "🍱	bento box\n" +
        "🧃	beverage box\n" +
        "🚴	bicyclist\n" +
        "👙	bikini\n" +
        "🧢	billed cap\n" +
        "🎱	billiards\n" +
        "☣️	biohazard sign\n" +
        "🐦	bird\n" +
        "🦬	bison\n" +
        "🫦	biting lip\n" +
        "♟️	black chess pawn\n" +
        "⏺️	black circle for record\n" +
        "♣️	black club suit\n" +
        "♦️	black diamond suit\n" +
        "⏬	black down-pointing double triangle\n" +
        "♥️	black heart suit\n" +
        "⬛	black large square\n" +
        "⏪	black left-pointing double triangle\n" +
        "⏮️	black left-pointing double triangle with vertical bar\n" +
        "◀️	black left-pointing triangle\n" +
        "◾	black medium small square\n" +
        "◼️	black medium square\n" +
        "✒️	black nib\n" +
        "⏩	black right-pointing double triangle\n" +
        "⏭️	black right-pointing double triangle with vertical bar\n" +
        "▶️	black right-pointing triangle\n" +
        "⏯️	black right-pointing triangle with double vertical bar\n" +
        "➡️	black rightwards arrow\n" +
        "✂️	black scissors\n" +
        "▪️	black small square\n" +
        "♠️	black spade suit\n" +
        "🔲	black square button\n" +
        "⏹️	black square for stop\n" +
        "☎️	black telephone\n" +
        "⏫	black up-pointing double triangle\n" +
        "🌼	blossom\n" +
        "🐡	blowfish\n" +
        "📘	blue book\n" +
        "🫐	blueberries\n" +
        "🐗	boar\n" +
        "💣	bomb\n" +
        "🦴	bone\n" +
        "📑	bookmark tabs\n" +
        "📚	books\n" +
        "🪃	boomerang\n" +
        "🍾	bottle with popping cork\n" +
        "💐	bouquet\n" +
        "🏹	bow and arrow\n" +
        "🥣	bowl with spoon\n" +
        "🎳	bowling\n" +
        "🥊	boxing glove\n" +
        "👦	boy\n" +
        "🍞	bread\n" +
        "🤱	breast-feeding\n" +
        "🧱	brick\n" +
        "👰	bride with veil\n" +
        "🌉	bridge at night\n" +
        "💼	briefcase\n" +
        "🩲	briefs\n" +
        "🥦	broccoli\n" +
        "🧹	broom\n" +
        "🤎	brown heart\n" +
        "🧋	bubble tea\n" +
        "🫧	bubbles\n" +
        "🪣	bucket\n" +
        "🐛	bug\n" +
        "🏗️	building construction\n" +
        "🌯	burrito\n" +
        "🚌	bus\n" +
        "🚏	bus stop\n" +
        "👤	bust in silhouette\n" +
        "👥	busts in silhouette\n" +
        "🧈	butter\n" +
        "🦋	butterfly\n" +
        "🤙	call me hand\n" +
        "📸	camera with flash\n" +
        "🏕️	camping\n" +
        "♋	cancer\n" +
        "🕯️	candle\n" +
        "🍬	candy\n" +
        "🥫	canned food\n" +
        "🛶	canoe\n" +
        "♑	capricorn\n" +
        "🗃️	card file box\n" +
        "📇	card index\n" +
        "🗂️	card index dividers\n" +
        "🎠	carousel horse\n" +
        "🎏	carp streamer\n" +
        "🪚	carpentry saw\n" +
        "🥕	carrot\n" +
        "🐈	cat\n" +
        "😹	cat face with tears of joy\n" +
        "😼	cat face with wry smile\n" +
        "⛓️	chains\n" +
        "🪑	chair\n" +
        "💹	chart with upwards trend and yen sign\n" +
        "📣	cheering megaphone\n" +
        "🏁	chequered flag\n" +
        "🍒	cherries\n" +
        "🌰	chestnut\n" +
        "🐔	chicken\n" +
        "🧒	child\n" +
        "🚸	children crossing\n" +
        "🐿️	chipmunk\n" +
        "🥢	chopsticks\n" +
        "🎄	christmas tree\n" +
        "⛪	church\n" +
        "🎦	cinema\n" +
        "🉑	circled ideograph accept\n" +
        "🉐	circled ideograph advantage\n" +
        "㊗️	circled ideograph congratulation\n" +
        "㊙️	circled ideograph secret\n" +
        "Ⓜ️	circled latin capital letter m\n" +
        "🎪	circus tent\n" +
        "🏙️	cityscape\n" +
        "🌆	cityscape at dusk\n" +
        "🎬	clapper board\n" +
        "🏛️	classical building\n" +
        "📋	clipboard\n" +
        "🕗	clock face eight oclock\n" +
        "🕣	clock face eight-thirty\n" +
        "🕚	clock face eleven oclock\n" +
        "🕦	clock face eleven-thirty\n" +
        "🕔	clock face five oclock\n" +
        "🕠	clock face five-thirty\n" +
        "🕓	clock face four oclock\n" +
        "🕟	clock face four-thirty\n" +
        "🕘	clock face nine oclock\n" +
        "🕤	clock face nine-thirty\n" +
        "🕐	clock face one oclock\n" +
        "🕜	clock face one-thirty\n" +
        "🕖	clock face seven oclock\n" +
        "🕢	clock face seven-thirty\n" +
        "🕕	clock face six oclock\n" +
        "🕡	clock face six-thirty\n" +
        "🕙	clock face ten oclock\n" +
        "🕥	clock face ten-thirty\n" +
        "🕒	clock face three oclock\n" +
        "🕞	clock face three-thirty\n" +
        "🕛	clock face twelve oclock\n" +
        "🕧	clock face twelve-thirty\n" +
        "🕑	clock face two oclock\n" +
        "🕝	clock face two-thirty\n" +
        "🔃	clockwise downwards and upwards open circle arrows\n" +
        "🔁	clockwise rightwards and leftwards open circle arrows\n" +
        "🔂	clockwise rightwards and leftwards open circle arrows with circled one overlay\n" +
        "📕	closed book\n" +
        "🔐	closed lock with key\n" +
        "📪	closed mailbox with lowered flag\n" +
        "📫	closed mailbox with raised flag\n" +
        "🌂	closed umbrella\n" +
        "🌩️	cloud with lightning\n" +
        "🌨️	cloud with snow\n" +
        "🌪️	cloud with tornado\n" +
        "🤡	clown face\n" +
        "🧥	coat\n" +
        "🪳	cockroach\n" +
        "🍸	cocktail glass\n" +
        "🥥	coconut\n" +
        "⚰️	coffin\n" +
        "🪙	coin\n" +
        "💥	collision symbol\n" +
        "☄️	comet\n" +
        "🧭	compass\n" +
        "🗜️	compression\n" +
        "😖	confounded face\n" +
        "😕	confused face\n" +
        "🚧	construction sign\n" +
        "👷	construction worker\n" +
        "🎛️	control knobs\n" +
        "🏪	convenience store\n" +
        "🍚	cooked rice\n" +
        "🍳	cooking\n" +
        "©️	copyright sign\n" +
        "🪸	coral\n" +
        "🛋️	couch and lamp\n" +
        "💑	couple with heart\n" +
        "🐄	cow\n" +
        "🦀	crab\n" +
        "🌙	crescent moon\n" +
        "🦗	cricket\n" +
        "🏏	cricket bat and ball\n" +
        "🐊	crocodile\n" +
        "🎌	crossed flags\n" +
        "⚔️	crossed swords\n" +
        "👑	crown\n" +
        "🩼	crutch\n" +
        "😿	crying cat face\n" +
        "🔮	crystal ball\n" +
        "🥒	cucumber\n" +
        "🧁	cupcake\n" +
        "🥌	curling stone\n" +
        "➰	curly loop\n" +
        "💱	currency exchange\n" +
        "🍛	curry and rice\n" +
        "🍮	custard\n" +
        "🛃	customs\n" +
        "🥩	cut of meat\n" +
        "🌀	cyclone\n" +
        "🗡️	dagger knife\n" +
        "💃	dancer\n" +
        "🍡	dango\n" +
        "🕶️	dark sunglasses\n" +
        "💨	dash symbol\n" +
        "🧏	deaf person\n" +
        "🦌	deer\n" +
        "🚚	delivery truck\n" +
        "🏬	department store\n" +
        "🏚️	derelict house building\n" +
        "🏜️	desert\n" +
        "🏝️	desert island\n" +
        "💠	diamond shape with a dot inside\n" +
        "😞	disappointed face\n" +
        "🥸	disguised face\n" +
        "🤿	diving mask\n" +
        "🪔	diya lamp\n" +
        "😵	dizzy face\n" +
        "🧬	dna double helix\n" +
        "🚯	do not litter symbol\n" +
        "🦤	dodo\n" +
        "🐕	dog\n" +
        "🐬	dolphin\n" +
        "🫏	donkey\n" +
        "🚪	door\n" +
        "🫥	dotted line face\n" +
        "➿	double curly loop\n" +
        "‼️	double exclamation mark\n" +
        "⏸️	double vertical bar\n" +
        "🕊️	dove of peace\n" +
        "🔻	down-pointing red triangle\n" +
        "🔽	down-pointing small red triangle\n" +
        "⬇️	downwards black arrow\n" +
        "🐉	dragon\n" +
        "🐲	dragon face\n" +
        "👗	dress\n" +
        "🐪	dromedary camel\n" +
        "🩸	drop of blood\n" +
        "💧	droplet\n" +
        "🥁	drum with drumsticks\n" +
        "🦆	duck\n" +
        "🥟	dumpling\n" +
        "📀	dvd\n" +
        "📧	e-mail symbol\n" +
        "🦅	eagle\n" +
        "👂	ear\n" +
        "🌽	ear of maize\n" +
        "🌾	ear of rice\n" +
        "🦻	ear with hearing aid\n" +
        "🥚	egg\n" +
        "✴️	eight pointed black star\n" +
        "✳️	eight spoked asterisk\n" +
        "⏏️	eject symbol\n" +
        "🔌	electric plug\n" +
        "🔦	electric torch\n" +
        "🐘	elephant\n" +
        "🛗	elevator\n" +
        "🧝	elf\n" +
        "🪹	empty nest\n" +
        "🔚	end with leftwards arrow above\n" +
        "✉️	envelope\n" +
        "📩	envelope with downwards arrow above\n" +
        "🏰	european castle\n" +
        "🏤	european post office\n" +
        "⁉️	exclamation question mark\n" +
        "👽	extraterrestrial alien\n" +
        "👁️	eye\n" +
        "👓	eyeglasses\n" +
        "🥹	face holding back tears\n" +
        "💆	face massage\n" +
        "🤦	face palm\n" +
        "😋	face savouring delicious food\n" +
        "🫩	face with bags under eyes\n" +
        "😓	face with cold sweat\n" +
        "🤠	face with cowboy hat\n" +
        "🫤	face with diagonal mouth\n" +
        "🤫	face with finger covering closed lips\n" +
        "🤕	face with head-bandage\n" +
        "😷	face with medical mask\n" +
        "🧐	face with monocle\n" +
        "🙅	face with no good gesture\n" +
        "🙆	face with ok gesture\n" +
        "🤨	face with one eyebrow raised\n" +
        "🫢	face with open eyes and hand over mouth\n" +
        "🤮	face with open mouth vomiting\n" +
        "🫣	face with peeking eye\n" +
        "😛	face with stuck-out tongue\n" +
        "😝	face with stuck-out tongue and tightly-closed eyes\n" +
        "🤒	face with thermometer\n" +
        "🥴	face with uneven eyes and wavy mouth\n" +
        "🏭	factory\n" +
        "🧚	fairy\n" +
        "🧆	falafel\n" +
        "🍂	fallen leaf\n" +
        "👪	family\n" +
        "🎅	father christmas\n" +
        "📠	fax machine\n" +
        "🪶	feather\n" +
        "♀️	female sign\n" +
        "🤺	fencer\n" +
        "🎡	ferris wheel\n" +
        "⛴️	ferry\n" +
        "🏑	field hockey stick and ball\n" +
        "🗄️	file cabinet\n" +
        "🎞️	film frames\n" +
        "📽️	film projector\n" +
        "🫆	fingerprint\n" +
        "🚒	fire engine\n" +
        "🧯	fire extinguisher\n" +
        "🧨	firecracker\n" +
        "🎇	firework sparkler\n" +
        "🎆	fireworks\n" +
        "🌓	first quarter moon symbol\n" +
        "🌛	first quarter moon with face\n" +
        "🐟	fish\n" +
        "🍥	fish cake with swirl design\n" +
        "🎣	fishing pole and fish\n" +
        "👊	fisted hand sign\n" +
        "⛳	flag in hole\n" +
        "🦩	flamingo\n" +
        "🥿	flat shoe\n" +
        "🫓	flatbread\n" +
        "⚜️	fleur-de-lis\n" +
        "🎴	flower playing cards\n" +
        "🪈	flute\n" +
        "🪰	fly\n" +
        "🥏	flying disc\n" +
        "🛸	flying saucer\n" +
        "🌫️	fog\n" +
        "🌁	foggy\n" +
        "🪭	folding hand fan\n" +
        "🫕	fondue\n" +
        "🦶	foot\n" +
        "🍴	fork and knife\n" +
        "🍽️	fork and knife with plate\n" +
        "🥠	fortune cookie\n" +
        "⛲	fountain\n" +
        "🖼️	frame with picture\n" +
        "🥶	freezing face\n" +
        "🍤	fried shrimp\n" +
        "🐥	front-facing baby chick\n" +
        "😦	frowning face with open mouth\n" +
        "⛽	fuel pump\n" +
        "🌕	full moon symbol\n" +
        "🌝	full moon with face\n" +
        "⚱️	funeral urn\n" +
        "🎲	game die\n" +
        "🧄	garlic\n" +
        "💎	gem stone\n" +
        "♊	gemini\n" +
        "🧞	genie\n" +
        "👻	ghost\n" +
        "🫚	ginger root\n" +
        "🦒	giraffe face\n" +
        "👧	girl\n" +
        "🥛	glass of milk\n" +
        "🌐	globe with meridians\n" +
        "🧤	gloves\n" +
        "🥅	goal net\n" +
        "🐐	goat\n" +
        "🥽	goggles\n" +
        "🏌️	golfer\n" +
        "🪿	goose\n" +
        "🦍	gorilla\n" +
        "🎓	graduation cap\n" +
        "🍇	grapes\n" +
        "🍏	green apple\n" +
        "📗	green book\n" +
        "🥗	green salad\n" +
        "🩶	grey heart\n" +
        "😬	grimacing face\n" +
        "😸	grinning cat face with smiling eyes\n" +
        "💗	growing heart\n" +
        "💂	guardsman\n" +
        "🦮	guide dog\n" +
        "🎸	guitar\n" +
        "🪮	hair pick\n" +
        "💇	haircut\n" +
        "🔨	hammer\n" +
        "⚒️	hammer and pick\n" +
        "🪬	hamsa\n" +
        "🐹	hamster face\n" +
        "🫰	hand with index finger and thumb crossed\n" +
        "👜	handbag\n" +
        "🤾	handball\n" +
        "🙋	happy person raising one hand\n" +
        "🪉	harp\n" +
        "🐣	hatching chick\n" +
        "🪦	headstone\n" +
        "🙉	hear-no-evil monkey\n" +
        "💟	heart decoration\n" +
        "💘	heart with arrow\n" +
        "💝	heart with ribbon\n" +
        "✔️	heavy check mark\n" +
        "➗	heavy division sign\n" +
        "💲	heavy dollar sign\n" +
        "🟰	heavy equals sign\n" +
        "⭕	heavy large circle\n" +
        "➖	heavy minus sign\n" +
        "✖️	heavy multiplication x\n" +
        "➕	heavy plus sign\n" +
        "🦔	hedgehog\n" +
        "🚁	helicopter\n" +
        "⛑️	helmet with white cross\n" +
        "🌿	herb\n" +
        "🔆	high brightness symbol\n" +
        "👠	high-heeled shoe\n" +
        "🚄	high-speed train\n" +
        "🚅	high-speed train with bullet nose\n" +
        "🥾	hiking boot\n" +
        "🛕	hindu temple\n" +
        "🦛	hippopotamus\n" +
        "🔪	hocho\n" +
        "🕳️	hole\n" +
        "🍯	honey pot\n" +
        "🐝	honeybee\n" +
        "🪝	hook\n" +
        "🚥	horizontal traffic light\n" +
        "🐎	horse\n" +
        "🐴	horse face\n" +
        "🏇	horse racing\n" +
        "🏥	hospital\n" +
        "🌭	hot dog\n" +
        "🌶️	hot pepper\n" +
        "♨️	hot springs\n" +
        "🏨	hotel\n" +
        "⌛	hourglass\n" +
        "🏘️	house buildings\n" +
        "🏡	house with garden\n" +
        "💯	hundred points symbol\n" +
        "😯	hushed face\n" +
        "🛖	hut\n" +
        "🪻	hyacinth\n" +
        "🍨	ice cream\n" +
        "🧊	ice cube\n" +
        "🏒	ice hockey stick and puck\n" +
        "⛸️	ice skate\n" +
        "🪪	identification card\n" +
        "👿	imp\n" +
        "📥	inbox tray\n" +
        "📨	incoming envelope\n" +
        "🫵	index pointing at the viewer\n" +
        "💁	information desk person\n" +
        "ℹ️	information source\n" +
        "🔠	input symbol for latin capital letters\n" +
        "🔤	input symbol for latin letters\n" +
        "🔡	input symbol for latin small letters\n" +
        "🔢	input symbol for numbers\n" +
        "🔣	input symbol for symbols\n" +
        "🏮	izakaya lantern\n" +
        "🎃	jack-o-lantern\n" +
        "🏯	japanese castle\n" +
        "🎎	japanese dolls\n" +
        "👺	japanese goblin\n" +
        "👹	japanese ogre\n" +
        "🏣	japanese post office\n" +
        "🔰	japanese symbol for beginner\n" +
        "🫙	jar\n" +
        "👖	jeans\n" +
        "🪼	jellyfish\n" +
        "🕹️	joystick\n" +
        "🤹	juggling\n" +
        "🕋	kaaba\n" +
        "🦘	kangaroo\n" +
        "🔟	keycap ten\n" +
        "🪯	khanda\n" +
        "👘	kimono\n" +
        "💏	kiss\n" +
        "💋	kiss mark\n" +
        "😽	kissing cat face with closed eyes\n" +
        "😚	kissing face with closed eyes\n" +
        "😙	kissing face with smiling eyes\n" +
        "🪁	kite\n" +
        "🥝	kiwifruit\n" +
        "🧎	kneeling person\n" +
        "🪢	knot\n" +
        "🥼	lab coat\n" +
        "🏷️	label\n" +
        "🥍	lacrosse stick and ball\n" +
        "🪜	ladder\n" +
        "🐞	lady beetle\n" +
        "🔵	large blue circle\n" +
        "🔷	large blue diamond\n" +
        "🟦	large blue square\n" +
        "🟤	large brown circle\n" +
        "🟫	large brown square\n" +
        "🟢	large green circle\n" +
        "🟩	large green square\n" +
        "🟠	large orange circle\n" +
        "🔶	large orange diamond\n" +
        "🟧	large orange square\n" +
        "🟣	large purple circle\n" +
        "🟪	large purple square\n" +
        "🔴	large red circle\n" +
        "🟥	large red square\n" +
        "🟡	large yellow circle\n" +
        "🟨	large yellow square\n" +
        "🌗	last quarter moon symbol\n" +
        "🌜	last quarter moon with face\n" +
        "✝️	latin cross\n" +
        "🍃	leaf fluttering in wind\n" +
        "🪾	leafless tree\n" +
        "🥬	leafy green\n" +
        "📒	ledger\n" +
        "🛅	left luggage\n" +
        "↔️	left right arrow\n" +
        "🗨️	left speech bubble\n" +
        "🤛	left-facing fist\n" +
        "↩️	leftwards arrow with hook\n" +
        "⬅️	leftwards black arrow\n" +
        "🫲	leftwards hand\n" +
        "🫷	leftwards pushing hand\n" +
        "🦵	leg\n" +
        "🍋	lemon\n" +
        "♌	leo\n" +
        "🐆	leopard\n" +
        "🎚️	level slider\n" +
        "♎	libra\n" +
        "🩵	light blue heart\n" +
        "🚈	light rail\n" +
        "🔗	link symbol\n" +
        "🖇️	linked paperclips\n" +
        "💄	lipstick\n" +
        "🦎	lizard\n" +
        "🦙	llama\n" +
        "🦞	lobster\n" +
        "🔏	lock with ink pen\n" +
        "🍭	lollipop\n" +
        "🪘	long drum\n" +
        "🧴	lotion bottle\n" +
        "🪷	lotus\n" +
        "🏩	love hotel\n" +
        "💌	love letter\n" +
        "🪫	low battery\n" +
        "🔅	low brightness symbol\n" +
        "🖊️	lower left ballpoint pen\n" +
        "🖍️	lower left crayon\n" +
        "🖋️	lower left fountain pen\n" +
        "🖌️	lower left paintbrush\n" +
        "🧳	luggage\n" +
        "🫁	lungs\n" +
        "🤥	lying face\n" +
        "🧙	mage\n" +
        "🪄	magic wand\n" +
        "🧲	magnet\n" +
        "🀄	mahjong tile red dragon\n" +
        "♂️	male sign\n" +
        "🦣	mammoth\n" +
        "👨	man\n" +
        "👫	man and woman holding hands\n" +
        "🕺	man dancing\n" +
        "🕴️	man in business suit levitating\n" +
        "🤵	man in tuxedo\n" +
        "👲	man with gua pi mao\n" +
        "👳	man with turban\n" +
        "🥭	mango\n" +
        "👞	mans shoe\n" +
        "🕰️	mantelpiece clock\n" +
        "🦽	manual wheelchair\n" +
        "🪇	maracas\n" +
        "🥋	martial arts uniform\n" +
        "🍖	meat on bone\n" +
        "⚫	medium black circle\n" +
        "⚪	medium white circle\n" +
        "🍈	melon\n" +
        "🫠	melting face\n" +
        "📝	memo\n" +
        "🕎	menorah with nine branches\n" +
        "🚹	mens symbol\n" +
        "🧜	merperson\n" +
        "🚇	metro\n" +
        "🦠	microbe\n" +
        "🎤	microphone\n" +
        "🔬	microscope\n" +
        "🪖	military helmet\n" +
        "🎖️	military medal\n" +
        "🌌	milky way\n" +
        "🚐	minibus\n" +
        "💽	minidisc\n" +
        "🪞	mirror\n" +
        "🪩	mirror ball\n" +
        "📴	mobile phone off\n" +
        "📲	mobile phone with rightwards arrow at left\n" +
        "💸	money with wings\n" +
        "🤑	money-mouth face\n" +
        "🐒	monkey\n" +
        "🐵	monkey face\n" +
        "🚝	monorail\n" +
        "🥮	moon cake\n" +
        "🎑	moon viewing ceremony\n" +
        "🫎	moose\n" +
        "🕌	mosque\n" +
        "🦟	mosquito\n" +
        "🤶	mother christmas\n" +
        "🛥️	motor boat\n" +
        "🛵	motor scooter\n" +
        "🦼	motorized wheelchair\n" +
        "🛣️	motorway\n" +
        "🗻	mount fuji\n" +
        "⛰️	mountain\n" +
        "🚵	mountain bicyclist\n" +
        "🚠	mountain cableway\n" +
        "🚞	mountain railway\n" +
        "🐁	mouse\n" +
        "🪤	mouse trap\n" +
        "👄	mouth\n" +
        "🎥	movie camera\n" +
        "🗿	moyai\n" +
        "🎶	multiple musical notes\n" +
        "🍄	mushroom\n" +
        "🎹	musical keyboard\n" +
        "🎵	musical note\n" +
        "🎼	musical score\n" +
        "📛	name badge\n" +
        "🏞️	national park\n" +
        "🤢	nauseated face\n" +
        "🧿	nazar amulet\n" +
        "👔	necktie\n" +
        "🆎	negative squared ab\n" +
        "❎	negative squared cross mark\n" +
        "🅰️	negative squared latin capital letter a\n" +
        "🅱️	negative squared latin capital letter b\n" +
        "🅾️	negative squared latin capital letter o\n" +
        "🅿️	negative squared latin capital letter p\n" +
        "🪺	nest with eggs\n" +
        "🪆	nesting dolls\n" +
        "🌑	new moon symbol\n" +
        "🌚	new moon with face\n" +
        "📰	newspaper\n" +
        "🌃	night with stars\n" +
        "🥷	ninja\n" +
        "🚳	no bicycles\n" +
        "⛔	no entry\n" +
        "🚫	no entry sign\n" +
        "📵	no mobile phones\n" +
        "🔞	no one under eighteen symbol\n" +
        "🚷	no pedestrians\n" +
        "🚭	no smoking symbol\n" +
        "🚱	non-potable water symbol\n" +
        "↗️	north east arrow\n" +
        "↖️	north west arrow\n" +
        "👃	nose\n" +
        "📓	notebook\n" +
        "📔	notebook with decorative cover\n" +
        "🔩	nut and bolt\n" +
        "🛑	octagonal sign\n" +
        "🐙	octopus\n" +
        "🍢	oden\n" +
        "🛢️	oil drum\n" +
        "🗝️	old key\n" +
        "🧓	older adult\n" +
        "👴	older man\n" +
        "👵	older woman\n" +
        "🫒	olive\n" +
        "🕉️	om symbol\n" +
        "🔛	on with exclamation mark with left right arrow above\n" +
        "🚘	oncoming automobile\n" +
        "🚍	oncoming bus\n" +
        "🚔	oncoming police car\n" +
        "🚖	oncoming taxi\n" +
        "🩱	one-piece swimsuit\n" +
        "🧅	onion\n" +
        "📖	open book\n" +
        "📭	open mailbox with lowered flag\n" +
        "📬	open mailbox with raised flag\n" +
        "⛎	ophiuchus\n" +
        "💿	optical disc\n" +
        "📙	orange book\n" +
        "🦧	orangutan\n" +
        "☦️	orthodox cross\n" +
        "🦦	otter\n" +
        "📤	outbox tray\n" +
        "🥵	overheated face\n" +
        "🦉	owl\n" +
        "🐂	ox\n" +
        "🦪	oyster\n" +
        "📦	package\n" +
        "📃	page with curl\n" +
        "📟	pager\n" +
        "🫳	palm down hand\n" +
        "🫴	palm up hand\n" +
        "🤲	palms up together\n" +
        "🥞	pancakes\n" +
        "🪂	parachute\n" +
        "🦜	parrot\n" +
        "〽️	part alternation mark\n" +
        "🛳️	passenger ship\n" +
        "🛂	passport control\n" +
        "🐾	paw prints\n" +
        "🫛	pea pod\n" +
        "☮️	peace symbol\n" +
        "🍑	peach\n" +
        "🦚	peacock\n" +
        "🥜	peanuts\n" +
        "🍐	pear\n" +
        "🚶	pedestrian\n" +
        "✏️	pencil\n" +
        "🐧	penguin\n" +
        "🫂	people hugging\n" +
        "🎭	performing arts\n" +
        "♾️	permanent paper sign\n" +
        "😣	persevering face\n" +
        "🙇	person bowing deeply\n" +
        "🧗	person climbing\n" +
        "🤸	person doing cartwheel\n" +
        "🙍	person frowning\n" +
        "🧘	person in lotus position\n" +
        "🧖	person in steamy room\n" +
        "⛹️	person with ball\n" +
        "👱	person with blond hair\n" +
        "🫅	person with crown\n" +
        "🧕	person with headscarf\n" +
        "🙎	person with pouting face\n" +
        "🧫	petri dish\n" +
        "⛏️	pick\n" +
        "🛻	pickup truck\n" +
        "🥧	pie\n" +
        "🐖	pig\n" +
        "🐽	pig nose\n" +
        "💩	pile of poo\n" +
        "💊	pill\n" +
        "🪅	pinata\n" +
        "🤏	pinching hand\n" +
        "🎍	pine decoration\n" +
        "🍍	pineapple\n" +
        "🩷	pink heart\n" +
        "♓	pisces\n" +
        "🔫	pistol\n" +
        "🪧	placard\n" +
        "🛐	place of worship\n" +
        "🛝	playground slide\n" +
        "🃏	playing card black joker\n" +
        "🪠	plunger\n" +
        "🚓	police car\n" +
        "🚨	police cars revolving light\n" +
        "👮	police officer\n" +
        "🐩	poodle\n" +
        "🍿	popcorn\n" +
        "📯	postal horn\n" +
        "📮	postbox\n" +
        "🍲	pot of food\n" +
        "🚰	potable water symbol\n" +
        "🥔	potato\n" +
        "🪴	potted plant\n" +
        "👝	pouch\n" +
        "🍗	poultry leg\n" +
        "🫗	pouring liquid\n" +
        "😾	pouting cat face\n" +
        "📿	prayer beads\n" +
        "🫃	pregnant man\n" +
        "🫄	pregnant person\n" +
        "🤰	pregnant woman\n" +
        "🥨	pretzel\n" +
        "🤴	prince\n" +
        "👸	princess\n" +
        "🦯	probing cane\n" +
        "📢	public address loudspeaker\n" +
        "👛	purse\n" +
        "🚮	put litter in its place symbol\n" +
        "🐇	rabbit\n" +
        "🦝	raccoon\n" +
        "🏎️	racing car\n" +
        "🏍️	racing motorcycle\n" +
        "📻	radio\n" +
        "🔘	radio button\n" +
        "☢️	radioactive sign\n" +
        "🚃	railway car\n" +
        "🛤️	railway track\n" +
        "🌈	rainbow\n" +
        "🤚	raised back of hand\n" +
        "✊	raised fist\n" +
        "✋	raised hand\n" +
        "🖐️	raised hand with fingers splayed\n" +
        "🖖	raised hand with part between middle and ring fingers\n" +
        "🐏	ram\n" +
        "🐀	rat\n" +
        "🪒	razor\n" +
        "🧾	receipt\n" +
        "🚙	recreational vehicle\n" +
        "🧧	red gift envelope\n" +
        "®️	registered sign\n" +
        "🎗️	reminder ribbon\n" +
        "🚻	restroom\n" +
        "🖕	reversed hand with middle finger extended\n" +
        "🦏	rhinoceros\n" +
        "🎀	ribbon\n" +
        "🍙	rice ball\n" +
        "🍘	rice cracker\n" +
        "🗯️	right anger bubble\n" +
        "🤜	right-facing fist\n" +
        "🔎	right-pointing magnifying glass\n" +
        "↪️	rightwards arrow with hook\n" +
        "🫱	rightwards hand\n" +
        "🫸	rightwards pushing hand\n" +
        "💍	ring\n" +
        "🛟	ring buoy\n" +
        "🪐	ringed planet\n" +
        "🍠	roasted sweet potato\n" +
        "🤖	robot face\n" +
        "🪨	rock\n" +
        "🧻	roll of paper\n" +
        "🗞️	rolled-up newspaper\n" +
        "🎢	roller coaster\n" +
        "🛼	roller skate\n" +
        "🐓	rooster\n" +
        "🫜	root vegetable\n" +
        "🏵️	rosette\n" +
        "📍	round pushpin\n" +
        "🚣	rowboat\n" +
        "🏉	rugby football\n" +
        "🏃	runner\n" +
        "🎽	running shirt with sash\n" +
        "🧷	safety pin\n" +
        "🦺	safety vest\n" +
        "♐	sagittarius\n" +
        "⛵	sailboat\n" +
        "🍶	sake bottle and cup\n" +
        "🧂	salt shaker\n" +
        "🫡	saluting face\n" +
        "🥪	sandwich\n" +
        "🥻	sari\n" +
        "🛰️	satellite\n" +
        "🦕	sauropod\n" +
        "🎷	saxophone\n" +
        "⚖️	scales\n" +
        "🧣	scarf\n" +
        "🏫	school\n" +
        "🎒	school satchel\n" +
        "🦂	scorpion\n" +
        "♏	scorpius\n" +
        "🪛	screwdriver\n" +
        "📜	scroll\n" +
        "🦭	seal\n" +
        "💺	seat\n" +
        "🥈	second place medal\n" +
        "🙈	see-no-evil monkey\n" +
        "🤳	selfie\n" +
        "🪡	sewing needle\n" +
        "🫨	shaking face\n" +
        "🥘	shallow pan of food\n" +
        "☘️	shamrock\n" +
        "🦈	shark\n" +
        "🍧	shaved ice\n" +
        "🐑	sheep\n" +
        "🛡️	shield\n" +
        "⛩️	shinto shrine\n" +
        "🚢	ship\n" +
        "🌠	shooting star\n" +
        "🛍️	shopping bags\n" +
        "🛒	shopping trolley\n" +
        "🩳	shorts\n" +
        "🪏	shovel\n" +
        "🚿	shower\n" +
        "🦐	shrimp\n" +
        "🤷	shrug\n" +
        "🗾	silhouette of japan\n" +
        "🔯	six pointed star with middle dot\n" +
        "🛹	skateboard\n" +
        "🎿	ski and ski boot\n" +
        "⛷️	skier\n" +
        "🦨	skunk\n" +
        "🛷	sled\n" +
        "🛌	sleeping accommodation\n" +
        "💤	sleeping symbol\n" +
        "🕵️	sleuth or spy\n" +
        "🙁	slightly frowning face\n" +
        "🎰	slot machine\n" +
        "🦥	sloth\n" +
        "🛩️	small airplane\n" +
        "🔹	small blue diamond\n" +
        "🔸	small orange diamond\n" +
        "😻	smiling cat face with heart-shaped eyes\n" +
        "😺	smiling cat face with open mouth\n" +
        "😇	smiling face with halo\n" +
        "😈	smiling face with horns\n" +
        "🤭	smiling face with smiling eyes and hand covering mouth\n" +
        "🥲	smiling face with tear\n" +
        "🚬	smoking symbol\n" +
        "🐌	snail\n" +
        "🐍	snake\n" +
        "🤧	sneezing face\n" +
        "🏔️	snow capped mountain\n" +
        "🏂	snowboarder\n" +
        "☃️	snowman\n" +
        "⛄	snowman without snow\n" +
        "⚽	soccer ball\n" +
        "🧦	socks\n" +
        "🍦	soft ice cream\n" +
        "🥎	softball\n" +
        "🔜	soon with rightwards arrow above\n" +
        "↘️	south east arrow\n" +
        "↙️	south west arrow\n" +
        "🍝	spaghetti\n" +
        "❇️	sparkle\n" +
        "💖	sparkling heart\n" +
        "🙊	speak-no-evil monkey\n" +
        "🔈	speaker\n" +
        "🔇	speaker with cancellation stroke\n" +
        "🔉	speaker with one sound wave\n" +
        "🔊	speaker with three sound waves\n" +
        "🗣️	speaking head in silhouette\n" +
        "💬	speech balloon\n" +
        "🚤	speedboat\n" +
        "🕷️	spider\n" +
        "🕸️	spider web\n" +
        "🗓️	spiral calendar pad\n" +
        "🗒️	spiral note pad\n" +
        "🐚	spiral shell\n" +
        "💦	splashing sweat symbol\n" +
        "🫟	splatter\n" +
        "🧽	sponge\n" +
        "🧵	spool of thread\n" +
        "🥄	spoon\n" +
        "🏅	sports medal\n" +
        "🐳	spouting whale\n" +
        "🈹	squared cjk unified ideograph-5272\n" +
        "🈴	squared cjk unified ideograph-5408\n" +
        "🈺	squared cjk unified ideograph-55b6\n" +
        "🈯	squared cjk unified ideograph-6307\n" +
        "🈷️	squared cjk unified ideograph-6708\n" +
        "🈶	squared cjk unified ideograph-6709\n" +
        "🈵	squared cjk unified ideograph-6e80\n" +
        "🈚	squared cjk unified ideograph-7121\n" +
        "🈸	squared cjk unified ideograph-7533\n" +
        "🈲	squared cjk unified ideograph-7981\n" +
        "🈳	squared cjk unified ideograph-7a7a\n" +
        "🆑	squared cl\n" +
        "🆒	squared cool\n" +
        "🆓	squared free\n" +
        "🆔	squared id\n" +
        "🈁	squared katakana koko\n" +
        "🈂️	squared katakana sa\n" +
        "🆖	squared ng\n" +
        "🆘	squared sos\n" +
        "🆙	squared up with exclamation mark\n" +
        "🆚	squared vs\n" +
        "🦑	squid\n" +
        "🏟️	stadium\n" +
        "⚕️	staff of aesculapius\n" +
        "🧍	standing person\n" +
        "☪️	star and crescent\n" +
        "✡️	star of david\n" +
        "🚉	station\n" +
        "🗽	statue of liberty\n" +
        "🚂	steam locomotive\n" +
        "🍜	steaming bowl\n" +
        "🩺	stethoscope\n" +
        "⏱️	stopwatch\n" +
        "📏	straight ruler\n" +
        "🍓	strawberry\n" +
        "🎙️	studio microphone\n" +
        "🥙	stuffed flatbread\n" +
        "⛅	sun behind cloud\n" +
        "🌞	sun with face\n" +
        "🌅	sunrise\n" +
        "🌄	sunrise over mountains\n" +
        "🌇	sunset over buildings\n" +
        "🦸	superhero\n" +
        "🦹	supervillain\n" +
        "🏄	surfer\n" +
        "🚟	suspension railway\n" +
        "🦢	swan\n" +
        "🏊	swimmer\n" +
        "🕍	synagogue\n" +
        "💉	syringe\n" +
        "🦖	t-rex\n" +
        "👕	t-shirt\n" +
        "🏓	table tennis paddle and ball\n" +
        "🥡	takeout box\n" +
        "🫔	tamale\n" +
        "🎋	tanabata tree\n" +
        "🍊	tangerine\n" +
        "♉	taurus\n" +
        "🍵	teacup without handle\n" +
        "🫖	teapot\n" +
        "📆	tear-off calendar\n" +
        "🧸	teddy bear\n" +
        "📞	telephone receiver\n" +
        "🔭	telescope\n" +
        "📺	television\n" +
        "🎾	tennis racquet and ball\n" +
        "⛺	tent\n" +
        "🧪	test tube\n" +
        "🌡️	thermometer\n" +
        "🥉	third place medal\n" +
        "🩴	thong sandal\n" +
        "💭	thought balloon\n" +
        "🎫	ticket\n" +
        "🐅	tiger\n" +
        "🐯	tiger face\n" +
        "⏲️	timer clock\n" +
        "😫	tired face\n" +
        "🚽	toilet\n" +
        "🗼	tokyo tower\n" +
        "🍅	tomato\n" +
        "👅	tongue\n" +
        "🧰	toolbox\n" +
        "🦷	tooth\n" +
        "🪥	toothbrush\n" +
        "🎩	top hat\n" +
        "🖲️	trackball\n" +
        "🚜	tractor\n" +
        "™️	trade mark sign\n" +
        "🚆	train\n" +
        "🚊	tram\n" +
        "🚋	tram car\n" +
        "🚩	triangular flag on post\n" +
        "📐	triangular ruler\n" +
        "🔱	trident emblem\n" +
        "🧌	troll\n" +
        "🚎	trolleybus\n" +
        "🍹	tropical drink\n" +
        "🐠	tropical fish\n" +
        "🎺	trumpet\n" +
        "🥃	tumbler glass\n" +
        "🦃	turkey\n" +
        "🐢	turtle\n" +
        "🔀	twisted rightwards arrows\n" +
        "👬	two men holding hands\n" +
        "👭	two women holding hands\n" +
        "☂️	umbrella\n" +
        "⛱️	umbrella on ground\n" +
        "☔	umbrella with rain drops\n" +
        "😒	unamused face\n" +
        "🦄	unicorn face\n" +
        "↕️	up down arrow\n" +
        "🔺	up-pointing red triangle\n" +
        "🔼	up-pointing small red triangle\n" +
        "⬆️	upwards black arrow\n" +
        "🧛	vampire\n" +
        "🚦	vertical traffic light\n" +
        "📳	vibration mode\n" +
        "📹	video camera\n" +
        "🎮	video game\n" +
        "📼	videocassette\n" +
        "🎻	violin\n" +
        "♍	virgo\n" +
        "🌋	volcano\n" +
        "🏐	volleyball\n" +
        "🧇	waffle\n" +
        "🌘	waning crescent moon symbol\n" +
        "🌖	waning gibbous moon symbol\n" +
        "🗑️	wastebasket\n" +
        "🐃	water buffalo\n" +
        "🚾	water closet\n" +
        "🤽	water polo\n" +
        "🌊	water wave\n" +
        "🍉	watermelon\n" +
        "🏴	waving black flag\n" +
        "🏳️	waving white flag\n" +
        "〰️	wavy dash\n" +
        "🌒	waxing crescent moon symbol\n" +
        "🌔	waxing gibbous moon symbol\n" +
        "🙀	weary cat face\n" +
        "😩	weary face\n" +
        "💒	wedding\n" +
        "🏋️	weight lifter\n" +
        "🐋	whale\n" +
        "🛞	wheel\n" +
        "☸️	wheel of dharma\n" +
        "♿	wheelchair symbol\n" +
        "👇	white down pointing backhand index\n" +
        "❕	white exclamation mark ornament\n" +
        "💮	white flower\n" +
        "☹️	white frowning face\n" +
        "⬜	white large square\n" +
        "👈	white left pointing backhand index\n" +
        "◽	white medium small square\n" +
        "◻️	white medium square\n" +
        "❔	white question mark ornament\n" +
        "👉	white right pointing backhand index\n" +
        "▫️	white small square\n" +
        "☺️	white smiling face\n" +
        "🔳	white square button\n" +
        "🌥️	white sun behind cloud\n" +
        "🌦️	white sun behind cloud with rain\n" +
        "👆	white up pointing backhand index\n" +
        "☝️	white up pointing index\n" +
        "🥀	wilted flower\n" +
        "🌬️	wind blowing face\n" +
        "🎐	wind chime\n" +
        "🪟	window\n" +
        "🪽	wing\n" +
        "🛜	wireless\n" +
        "🐺	wolf face\n" +
        "👩	woman\n" +
        "👯	woman with bunny ears\n" +
        "👢	womans boots\n" +
        "👚	womans clothes\n" +
        "👒	womans hat\n" +
        "👡	womans sandal\n" +
        "🚺	womens symbol\n" +
        "🪵	wood\n" +
        "🪱	worm\n" +
        "😟	worried face\n" +
        "🔧	wrench\n" +
        "🤼	wrestlers\n" +
        "🩻	x-ray\n" +
        "🥱	yawning face\n" +
        "☯️	yin yang\n" +
        "🪀	yo-yo\n" +
        "🦓	zebra face\n" +
        "🤐	zipper-mouth face\n" +
        "🧟	zombie";

    /// <summary>Scalars that take a skin tone (Emoji_Modifier_Base), hex, family U+1F46A excluded.</summary>
    public const string ModifierBases = "261D 26F9 270A 270B 270C 270D 1F385 1F3C2 1F3C3 1F3C4 1F3C7 1F3CA 1F3CB 1F3CC 1F442 1F443 1F446 1F447 1F448 1F449 1F44A 1F44B 1F44C 1F44D 1F44E 1F44F 1F450 1F466 1F467 1F468 1F469 1F46B 1F46C 1F46D 1F46E 1F470 1F471 1F472 1F473 1F474 1F475 1F476 1F477 1F478 1F47C 1F481 1F482 1F483 1F485 1F486 1F487 1F4AA 1F574 1F575 1F57A 1F590 1F595 1F596 1F645 1F646 1F647 1F64B 1F64C 1F64D 1F64E 1F64F 1F6A3 1F6B4 1F6B5 1F6B6 1F6C0 1F6CC 1F90C 1F90F 1F918 1F919 1F91A 1F91B 1F91C 1F91E 1F91F 1F926 1F930 1F931 1F932 1F933 1F934 1F935 1F936 1F937 1F938 1F939 1F93D 1F93E 1F977 1F9B5 1F9B6 1F9B8 1F9B9 1F9BB 1F9CD 1F9CE 1F9CF 1F9D1 1F9D2 1F9D3 1F9D4 1F9D5 1F9D6 1F9D7 1F9D8 1F9D9 1F9DA 1F9DB 1F9DC 1F9DD 1FAC3 1FAC4 1FAC5 1FAF0 1FAF1 1FAF2 1FAF3 1FAF4 1FAF5 1FAF6 1FAF7 1FAF8";
}
