#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerates EmojiData.g.cs and TimeZoneData.g.cs (spec 06 §6.10, §6.12.3).

Usage: python3 -I generate_data.py <emoji-test.txt> <zone.tab> <output-dir>

* Emoji names come from the Unicode Character Database of the running Python
  (unicodedata, Unicode 16 for Python 3.14), lower-cased, the same names the
  macOS app reads through ICU's Any-Name transform.
* The emoji set is every single-scalar emoji listed in emoji-test.txt plus
  the scalars added later in the Supplemental Symbols and Pictographs and
  Symbols and Pictographs Extended-A blocks (all of which are emoji).
* Time zones: every identifier of zone.tab plus GMT and UTC.
"""
import sys
import unicodedata

POPULAR = (
    "😀 😃 😄 😁 😆 😅 🤣 😂 🙂 🙃 😉 😊 😍 🥰 😘 😗 😜 🤪 🤔 🤗 🤩 🥳 😎 🤓 😐 😑 😶 🙄 😏 😥 😮 😴 😌 😔 "
    "😪 🤤 😭 😢 😤 😠 😡 🤬 🤯 😳 🥺 😱 😨 😰 💀 ☠️ 🙏 👍 👎 👌 🤌 ✌️ 🤞 🤟 🤘 👏 🙌 👐 💪 🫶 👋 🤝 ✍️ "
    "💅 👀 🧠 🫀 🦾 🦿 👣 ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 💔 ❣️ 💕 💞 🔥 ✨ ⭐️ 🌟 💫 ⚡️ ☀️ 🌤 ☁️ 🌧 ⛈ ❄️ 🎉 🎊 "
    "🎁 🎂 🍰 🍕 🍔 🍟 🌮 🍣 🍎 🍌 ☕️ 🍺 🍻 🥂 🍷 🧉 🥤 🍫 🍪 🍩 🥐 🧀 🚀 ✈️ 🚗 🚕 🚲 🛴 🏠 🏢 🌍 🌎 🌏 🗺 "
    "💻 🖥 ⌨️ 🖱 📱 ⌚️ 🎧 📷 🔋 💾 🖨 📡 📁 📂 📄 📌 📎 🔖 🔍 🔒 🔓 🔑 🛠 ⚙️ ✅ ❌ ⚠️ ❓ ❗️ 💡 🔔 🔕 ♻️ "
    "🆗 🆕 🔝 🐶 🐱 🐭 🐰 🦊 🐻 🐼 🐨 🦁 🐮 🐷 🐸 🌱 🌲 🌳 🌴 🌵 🌷 🌸 🌹 🌺 🌻 🍀 🍁 ⏰ ⏳ 📅 📈 📉 📊 💰 "
    "💳 🏆 🥇 🎯 🧩"
).split()

EXCLUDED = set(range(0x1F3FB, 0x1F400)) | set(range(0x1F1E6, 0x1F200)) | set(range(0x1F9B0, 0x1F9B4))
EXCLUDED |= {ord(c) for c in "#*0123456789"} | {0x200D, 0x20E3, 0xFE0F, 0xFE0E}
NOT_EMOJI_IN_BLOCKS = set(range(0x1F900, 0x1F90C)) | {0x1F93B, 0x1F946}
LATER_SINGLE = [0x1F6D6, 0x1F6D7, 0x1F6DC, 0x1F6DD, 0x1F6DE, 0x1F6DF, 0x1F6FB, 0x1F6FC, 0x1F7F0]
LATER_MODIFIER_BASES = [0x1F90C, 0x1F977, 0x1FAC3, 0x1FAC4, 0x1FAC5] + list(range(0x1FAF0, 0x1FAF9))


def scalar_name(cp):
    try:
        return unicodedata.name(chr(cp)).lower()
    except ValueError:
        return None


def sequence_name(text):
    parts = []
    for ch in text:
        cp = ord(ch)
        if cp in (0xFE0E, 0xFE0F):
            continue
        name = scalar_name(cp)
        if name is None or name.startswith("zero width"):
            continue
        parts.append(name)
    return " ".join(parts)


def main(emoji_test, zone_tab, out_dir):
    singles = {}          # cp -> text default (needs FE0F)
    modifier_bases = set(LATER_MODIFIER_BASES)
    for line in open(emoji_test, encoding="utf-8"):
        if not line.strip() or line.startswith("#") or ";" not in line:
            continue
        codes = [int(c, 16) for c in line.split(";")[0].split()]
        status = line.split(";")[1].split("#")[0].strip()
        if len(codes) == 2 and codes[1] in range(0x1F3FB, 0x1F400):
            modifier_bases.add(codes[0])
        if len(codes) == 1 and status in ("fully-qualified", "unqualified", "minimally-qualified", "component"):
            singles.setdefault(codes[0], False)
        if len(codes) == 2 and codes[1] == 0xFE0F and status == "fully-qualified":
            singles[codes[0]] = True

    for cp in list(range(0x1F900, 0x1FA00)) + list(range(0x1FA70, 0x1FB00)) + LATER_SINGLE:
        if cp in singles or cp in NOT_EMOJI_IN_BLOCKS:
            continue
        name = scalar_name(cp)
        if name and unicodedata.category(chr(cp)) == "So":
            singles[cp] = False

    popular_keys = {p.replace("️", "").replace("︎", "") for p in POPULAR}
    tail = []
    for cp, text_default in singles.items():
        if cp in EXCLUDED or cp > 0x1FAFF:
            continue
        name = scalar_name(cp)
        if not name:
            continue
        glyph = chr(cp) + ("️" if text_default else "")
        if chr(cp) in popular_keys:
            continue
        tail.append((name, glyph))
    tail.sort()

    def quote(text):
        return text.replace("\\", "\\\\").replace("\"", "\\\"")

    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// <auto-generated> by CommandBar/Data/generate_data.py from the Unicode Character Database",
        f"// (Unicode {unicodedata.unidata_version}) and emoji-test.txt. Do not edit by hand.",
        "namespace Rivet.Core.Launcher;",
        "",
        "internal static class EmojiData",
        "{",
        "    /// <summary>Popular emoji in display order: \"glyph\\tname\" lines.</summary>",
        "    public const string Popular =",
    ]
    popular_rows = [f"{p}\t{sequence_name(p)}" for p in POPULAR]
    lines += [f"        \"{quote(r)}\\n\" +" for r in popular_rows[:-1]] + [f"        \"{quote(popular_rows[-1])}\";", ""]
    lines += ["    /// <summary>Every other emoji scalar, sorted by name: \"glyph\\tname\" lines.</summary>", "    public const string LongTail ="]
    tail_rows = [f"{g}\t{n}" for n, g in tail]
    lines += [f"        \"{quote(r)}\\n\" +" for r in tail_rows[:-1]] + [f"        \"{quote(tail_rows[-1])}\";", ""]
    bases = " ".join(f"{cp:X}" for cp in sorted(modifier_bases) if cp != 0x1F46A)
    lines += ["    /// <summary>Scalars that take a skin tone (Emoji_Modifier_Base), hex, family U+1F46A excluded.</summary>",
              f"    public const string ModifierBases = \"{bases}\";", "}", ""]
    with open(f"{out_dir}/EmojiData.g.cs", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    zones = sorted({l.split("\t")[2].strip() for l in open(zone_tab) if not l.startswith("#") and l.strip()} | {"GMT", "UTC"})
    zone_lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// <auto-generated> by CommandBar/Data/generate_data.py from the tz database zone.tab. Do not edit by hand.",
        "namespace Rivet.Core.Snippets;",
        "",
        "internal static class TimeZoneData",
        "{",
        "    /// <summary>Known IANA identifiers, sorted, separated by spaces.</summary>",
        "    public const string Identifiers =",
    ]
    chunks = [" ".join(zones[i:i + 8]) for i in range(0, len(zones), 8)]
    zone_lines += [f"        \"{c} \" +" for c in chunks[:-1]] + [f"        \"{chunks[-1]}\";", "}", ""]
    with open(f"{out_dir}/TimeZoneData.g.cs", "w", encoding="utf-8") as f:
        f.write("\n".join(zone_lines))
    print(f"{len(POPULAR)} popular, {len(tail)} long tail, {len(modifier_bases)} modifier bases, {len(zones)} zones")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
