#!/usr/bin/env python3
"""Prototype: generate a Swift `main.swift` that dumps every localized string
catalog of the Vorssaint repo to JSON, plus the list of sources to compile.

Usage: python3 -I generate.py <repo-root> <out-dir>

Nothing is written inside the repo. The source list is the standalone,
AppKit-UI-free set that build.sh already compiles for its unit-test binary
(the TEST_SOURCES array), minus the Tests/ and build/ entries.
"""
import glob
import re
import sys
from pathlib import Path

repo = Path(sys.argv[1]).resolve()
out = Path(sys.argv[2]).resolve()
out.mkdir(parents=True, exist_ok=True)

# 1. Sources: reuse build.sh's TEST_SOURCES block.
build = (repo / "build.sh").read_text()
block = re.search(r"TEST_SOURCES=\(\n(.*?)\n\s*\)", build, re.S).group(1)
sources = []
for line in block.splitlines():
    entry = line.strip()
    if not entry or entry.startswith("Tests/") or entry.startswith("build/"):
        continue
    for path in sorted(glob.glob(str(repo / entry))):
        sources.append(path)
(out / "sources.txt").write_text("\n".join(sources) + "\n")

# 2. Catalog factories: the same discovery Tests/generate_sources.py uses,
#    i.e. every `static func name(_ x: AppLanguage) ->` inside an
#    `extension FeatureStrings { ... }` / `enum FeatureStrings { ... }` scope.
pattern = r"static\s+func\s+(\w+)\s*\(\s*_\s+\w+:\s*AppLanguage\s*\)\s*->"
factories = []
for path in sorted((repo / "Sources/Vorssaint/Core").glob("*Strings.swift")):
    src = path.read_text()
    if "extension FeatureStrings" in src or "enum FeatureStrings" in src:
        scopes = re.findall(r"(?:extension|enum) FeatureStrings \{(.*?)^\}", src, re.S | re.M)
        factories += [n for s in scopes for n in re.findall(pattern, s)]
factories = sorted(set(factories))

# Catalogs reached through their own `localized(_:)`, not through FeatureStrings.
standalone = [
    "MediaImageConverterStrings", "WindowDirectionalStrings", "PointerDisplayStrings",
    "GraphScaleStrings", "NotchLowBatteryStrings", "WhatsAppOrganizerStrings",
    "ShelfPromiseDeliveryStrings", "SettingsNavigationStrings",
]

lines = [
    "import Foundation",
    "",
    "// Generated by generate.py. Dumps catalog -> language -> key -> value.",
    "var catalogs: [String: [String: [String: String]]] = [:]",
    "var nonStringFields: [String] = []",
    "func add(_ name: String, _ make: (AppLanguage) -> Any) {",
    "    for language in AppLanguage.allCases {",
    "        var table: [String: String] = [:]",
    "        for child in Mirror(reflecting: make(language)).children {",
    "            guard let key = child.label else { continue }",
    "            if let text = child.value as? String { table[key] = text }",
    "            else if language == .enUS { nonStringFields.append(\"\\(name).\\(key)\") }",
    "        }",
    "        catalogs[name, default: [:]][language.rawValue] = table",
    "    }",
    "}",
    'add("Strings") { Strings.localized($0) }',
]
lines += [f'add("FeatureStrings.{n}") {{ FeatureStrings.{n}($0) }}' for n in factories]
lines += [f'add("{n}") {{ {n}.localized($0) }}' for n in standalone]
lines += [
    "let encoder = JSONEncoder()",
    "encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]",
    "let data = try! encoder.encode(catalogs)",
    "FileManager.default.createFile(atPath: CommandLine.arguments[1], contents: data)",
    "var total = 0, perLanguage = 0",
    "for (_, languages) in catalogs { perLanguage += languages[\"en-US\"]?.count ?? 0; total += languages.values.reduce(0) { $0 + $1.count } }",
    'print("catalogs: \\(catalogs.count), keys per language: \\(perLanguage), values: \\(total)")',
    'print("non-String fields skipped: \\(nonStringFields)")',
]
(out / "main.swift").write_text("\n".join(lines) + "\n")
print(f"{len(sources)} sources, {len(factories)} FeatureStrings factories, {len(standalone)} standalone catalogs")
